### ISSUE TITLE
Environment Variable Clarification

### ISSUE THREAD

**Issue by flawsom** [Miruro-no-kuon/Miruro#170]
why is still running on preview mode with skeletons, what am i doing wrong ? ( i followed it exactly as u instructed in the env's and without "" for the links )

![Screenshot (25)](https://github.com/Miruro-no-kuon/Miruro/assets/64182228/28cbbd74-55fc-4abf-89f3-4f99c23e3c8c)

**Comment by trying559** [comment]
Make sure to follow the instructions precisely and avoid removing any commas from the .env.example file. If issues persist, refer to the thread for further troubleshooting steps.

**Comment by flawsom** [comment]
still the same 
can we talk on discord ?

**Comment by flawsom** [comment]
Am I doing anything wrong here @trying559 @akionii 

![Screenshot_2024-03-23-22-25-25-52_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Miruro-no-kuon/Miruro/assets/64182228/94c048ac-0486-4394-ae46-40bdaf4b92a8)

**Comment by akionii** [comment]
Hey! Checked out the screenshot, and your setup looks **all good** to me. Spotted 'miruro2' in the URL, and when I looked up `miruro2.vercel.app`, I found a live app – could be yours, right?

If you're running into trouble getting things to work, take a look at the project's `readme`. You'll find a **Vercel Deploy** button there. Make sure to enter your env variables **exactly** as they're shown in your [`.env.example`](https://github.com/Miruro-no-kuon/Miruro/blob/main/.env.example).
. Stick to that, and you should see your app up and running in no time. 👐

And hey, just to make things a tad easier, here's the deploy button again for quick access:

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2FMiruro-no-kuon%2FMiruro&env=VITE_BACKEND_URL,VITE_PROXY_URL,VITE_IS_LOCAL,PORT&project-name=miruro&repository-name=miruro)

If you need any more help, just give a shout. 👋

**Comment by flawsom** [comment]
Even after adding it exactly as it was guided in the .env.example

Am still facing the similar issue at https://miruro3.vercel.app/

![Screenshot_2024-03-24-00-06-05-99_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Miruro-no-kuon/Miruro/assets/64182228/338a5407-186d-43f9-afee-3f9d08dec56e)

**Comment by akionii** [comment]
Hey again!

Remember, no need for **("")** quotes on Vercel deployment. You got this!

Also, just a heads-up, I'll be putting together a simple video guide on deploying with Miruro to make things even easier for you.

If you need any more help, just give me a shout. Cheers!

**Comment by flawsom** [comment]
I will be eagerly waiting for the video guide 

Can't seem to resolve this part with or without ""

**Comment by flawsom** [comment]
am still facing the issue here is it something with indian ip's?? @akionii  @trying559  


https://github.com/Miruro-no-kuon/Miruro/assets/64182228/2b14094b-aac4-4a27-b410-42293be574ea

**Comment by flawsom** [comment]
@trying559 @akionii still the same issue, 
Would there be any issues if i comment the corsproxy part out, is it switchable..?

**Comment by techroy23** [comment]
Hi @akionii I'm also getting the same error message. I want to have everything locally hosted on my own computer. I made changes to the .env file but got the same error. I tried hosting my own corsproxy but got the same error.

```
VITE_IS_LOCAL=true
VITE_LOCAL_IP=192.168.200.200
VITE_BACKEND_URL=http://localhost:3000
VITE_SKIP_TIMES=http://api.aniskip.com
VITE_PROXY_URL=https://corsproxy.io
PORT=60000
```


Please see all screenshot below
![image](https://github.com/Miruro-no-kuon/Miruro/assets/53241974/d6d59f31-a7ad-4835-893c-8e6491f1788f)
![image](https://github.com/Miruro-no-kuon/Miruro/assets/53241974/ff473743-8584-4706-bdd0-6d6ec527ca11)

**Comment by MaviMods** [comment]
> Hi @akionii I'm also getting the same error message. I want to have everything locally hosted on my own computer. I made changes to the .env file but got the same error. I tried hosting my own corsproxy but got the same error.
> 
> ```
> VITE_IS_LOCAL=true
> VITE_LOCAL_IP=192.168.200.200
> VITE_BACKEND_URL=http://localhost:3000
> VITE_SKIP_TIMES=http://api.aniskip.com
> VITE_PROXY_URL=https://corsproxy.io
> PORT=60000
> ```
> 
> Please see all screenshot below ![image](https://private-user-images.githubusercontent.com/53241974/318290247-d6d59f31-a7ad-4835-893c-8e6491f1788f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTU0NTgsIm5iZiI6MTcxMTkxNTE1OCwicGF0aCI6Ii81MzI0MTk3NC8zMTgyOTAyNDctZDZkNTlmMzEtYTdhZC00ODM1LTg5M2MtOGU2NDkxZjE3ODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE5NTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MzVhOTgzNWQzYjRmM2Q1MGRlYTUzODJiYWRlYzIzYzdmOGJhYTY5ZGJkNTgxYWJkODZmNzZhNDgyZjQyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jnmE-Zjhb23f2sNiq4kv-fgWm_1Dwdq9Sz6jTBQB69U) ![image](https://private-user-images.githubusercontent.com/53241974/318290365-ff473743-8584-4706-bdd0-6d6ec527ca11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTU0NTgsIm5iZiI6MTcxMTkxNTE1OCwicGF0aCI6Ii81MzI0MTk3NC8zMTgyOTAzNjUtZmY0NzM3NDMtODU4NC00NzA2LWJkZDAtNmQ2ZWM1MjdjYTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE5NTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZDUyODBmZjRiYjBkOGFkYzdkNTI5YTE5MmQ1ZjUyNzZlY2I3MWNiNTM3YzcxYjE0OTRjNzJmNDZkMzNiMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lnNqfWKw3V97NZPXHK1rU4J5P3NYaDOV0-thwFshNjs)

Hy bro thats proxy error you made consumet api not corsproxy!!

**Comment by akionii** [comment]
Hey everyone! 👋

Let's tackle a few things to smooth out our deployment and local development workflows. There's quite a bit to cover, so I'll dive straight in:

@flawsom, regarding the CORS proxy issue: if you're unable to find a service that works in your region, reach out to me directly. I can guide you on how to adjust the code to operate without the CORS proxy. Just a heads-up, this might result in a slower initial response time due to the lack of caching that `corsproxy.io` provides. If that's a trade-off you're willing to consider, I'm here to help.

@techroy23, thanks to @MaviMods for spotting the typo. It should be `corsproxy.io`, not `consumet`. However, the real culprit here is the missing trailing slashes for `VITE_BACKEND_URL` and `VITE_SKIP_TIMES`. They should both end with a "/", like this:

```plaintext
VITE_BACKEND_URL="http://localhost:3000/"
VITE_SKIP_TIMES="http://api.aniskip.com/"
```

Why the fuss over the trailing slash? Well, some servers interpret the paths differently if there's no trailing slash. It can lead to incorrect request handling or routing on the server-side, which in turn, causes 404 errors.

For everyone, I'm rolling out an update with a nifty little function, `ensureUrlEndsWithSlash`, which will append a slash to your URLs if they're missing one. This will help prevent routing issues and ensure our requests hit the right endpoints.

Here's a sneak peek at the function:

```javascript
// Ensures that all URLs end with a slash for consistency
function ensureUrlEndsWithSlash(url) {
  return url.endsWith('/') ? url : `${url}/`;
}
```

In the next commit, this function will be integrated, so you'll have one less thing to worry about.

Lastly, the latest `.env.example` looks like this:

```plaintext
VITE_BACKEND_URL="https://public-miruro-consumet-api.vercel.app/"
VITE_SKIP_TIMES="https://api.aniskip.com/"
VITE_PROXY_URL="https://corsproxy.io"
PORT=5173
```

Please note that `VITE_IS_LOCAL` and `VITE_LOCAL_IP` have been deprecated. Our app now auto-detects the local IP in production when you run `bun start`.

Remember, for any further clarification or assistance, I'm just a message away. Keep up the great work. And, as always, a huge shoutout to @MaviMods for the assist. 👍

Cheers,
@akionii

**Comment by techroy23** [comment]
@akionii can you also guide me what to adjust so i can run this without corsproxy?

**Comment by akionii** [comment]
**Sure!** I'll drop a guide in our Discord channel as soon as I can on how to get everything up and running without the need for a *CORS* **Proxy**. Keep an eye out! 👀

**Comment by techroy23** [comment]
@akionii i think we can tag this one as resolve for now. I tested the current build without corsproxy and it works.
