### ISSUE TITLE
Deployment Error: Command `npm install` exited with 1

### ISSUE THREAD

**Issue by rajuan-r34** [Miruro-no-kuon/Miruro#185]
Vercel Deployment error 
`Error: Command "npm install" exited with 1`

How to fix it

**Comment by MaviMods** [comment]
bun install && cd server && bun install use this install command!!

**Comment by akionii** [comment]
Hey @rajuan-r34,

Ran into trouble with `npm install`, huh? That's often because **Node.js isn't installed** yet. It's essential for our app.

Here's a **simple guide to install Node.js**:

1. Visit the [Node.js website](https://nodejs.org/).
2. Select the version labeled as *"long-term support"* or **LTM**.
3. Download and run the installer. Follow the prompts by clicking 'Next'.
4. To confirm it's installed, open your command line or terminal and type `node -v`. You should see the version number displayed.

Tell us your computer's OS (ex: Windows, Mac, Linux...), your Node.js version (ex: v20.12.0), and any more errors you're seeing. Like this:
-  *"I'm on Windows 10, running Node 14.2, and keep getting 'Error: Cannot find module'."*

Also, @MaviMods  **thanks** for your suggestion! Just a note: our latest update means there's no need to install anything in the `/server` folder now.

**Hope this helps!**
