### ISSUE TITLE
Fix hardcoded `PORT` configurable via .env var.

### ISSUE THREAD

**Issue by techroy23** [Miruro-no-kuon/Miruro#193]
the port "5173" is currently hardcoded in file https://github.com/Miruro-no-kuon/Miruro/blob/main/vite.config.ts and https://github.com/Miruro-no-kuon/Miruro/blob/main/server/server.ts it would be better if this can be moved to .env.

**Comment by akionii** [comment]
**Got it!** Just pushed the fix on the [**preview-main**](https://github.com/Miruro-no-kuon/Miruro/tree/preview-main) branch – the port's now in the .env file as `VITE_PORT`. Check out this [**commit:6a74ca0**](https://github.com/Miruro-no-kuon/Miruro/commit/6a74ca0408159d116751d3632ae84c20a5765d77).

Regarding the `server.ts` file, I ran into some issues due to a **bug** or perhaps a weird **syntax/configuration** issue with **Vite** that prevents a similar approach for the time being. I'll be looking for possible solutions and will update the thread once I have a fix.

Cheers!

**Comment by techroy23** [comment]
i will create a PR for preview branch later.

**Comment by techroy23** [comment]
Findings:

when bun changes directory to server. It cannot see the .env file anymore resulting to undefined value. which can be be debug by including a quick console log :-P  

```console.log(`Server running on port ${port}`);```

**Comment by akionii** [comment]
Awesome work on the port issue! I wondered why it didn't work, and it turned out to be a **bun issue** after all... 
Oh and really cool to have you as our **first outside contributor**. 😊 Thanks for jumping in and making this change—it's a big improvement.

I'm sorry for the delay in my response; I've been pretty busy the past couple of weeks.

Cheers!
